FROM docker.io/library/buildpack-deps:bookworm

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        bison \
        cmake \
        flex \
        gawk \
        gettext \
        meson \
        ninja-build \
        pkg-config \
        python3 \
        texinfo \
    && rm -rf /var/lib/apt/lists/*
