[package]
name = "bobr-bundle-launcher"
version.workspace = true
edition = "2024"
description = "Static launcher for programs packaged in a bobr HostBundle."
license.workspace = true
repository.workspace = true

[dependencies]
libc.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
