[build]
target-dir = "target"

[alias]
build-bundle-launcher-x86_64 = "build -p bobr-bundle-launcher --target x86_64-unknown-linux-musl"
build-bundle-launcher-aarch64 = "build -p bobr-bundle-launcher --target aarch64-unknown-linux-musl"
build-sandbox-launcher-x86_64 = "build -p bobr-sandbox-launcher --target x86_64-unknown-linux-musl"
build-sandbox-launcher-aarch64 = "build -p bobr-sandbox-launcher --target aarch64-unknown-linux-musl"
