use std::fmt;

/// Error returned when parsing a 32-byte lowercase-hex hash value.
///
/// Hash wrappers generated by `define_hex_hash_type!` use exactly 64
/// lowercase hexadecimal characters as their textual representation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ParseHexHashError {
    /// The input length is not exactly 64 bytes.
    InvalidLength,
    /// The input contains a byte outside `[0-9a-f]`.
    InvalidHex,
}

impl fmt::Display for ParseHexHashError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidLength => f.write_str("hash must contain 64 lowercase hex digits"),
            Self::InvalidHex => f.write_str("hash must contain only lowercase hex digits"),
        }
    }
}

impl std::error::Error for ParseHexHashError {}

/// Defines a public 32-byte hash wrapper with lowercase-hex text encoding.
///
/// The generated type stores a raw `[u8; 32]` digest, implements `Display`,
/// `Debug`, `FromStr`, `Serialize`, and `Deserialize`, and exposes `as_bytes`
/// and `to_hex` helpers. The generated `from_bytes` constructor is `pub(crate)`
/// so only the defining crate can construct values from raw bytes.
#[macro_export]
macro_rules! define_hex_hash_type {
    (
        $(#[$meta:meta])*
        pub struct $name:ident;
    ) => {
        $(#[$meta])*
        #[derive(Clone, Copy, PartialEq, Eq, Hash)]
        pub struct $name([u8; 32]);

        impl $name {
            pub(crate) fn from_bytes(bytes: [u8; 32]) -> Self {
                Self(bytes)
            }

            /// Returns the raw 32-byte digest.
            pub fn as_bytes(&self) -> &[u8; 32] {
                &self.0
            }

            /// Formats the value as 64 lowercase hexadecimal characters.
            pub fn to_hex(&self) -> String {
                let mut out = ::std::string::String::with_capacity(64);
                for byte in self.0 {
                    out.push(b"0123456789abcdef"[(byte >> 4) as usize] as char);
                    out.push(b"0123456789abcdef"[(byte & 0x0f) as usize] as char);
                }
                out
            }
        }

        impl ::std::fmt::Display for $name {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                for byte in self.0 {
                    write!(f, "{byte:02x}")?;
                }
                Ok(())
            }
        }

        impl ::std::fmt::Debug for $name {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                f.debug_tuple(stringify!($name))
                    .field(&self.to_hex())
                    .finish()
            }
        }

        impl ::serde::Serialize for $name {
            fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
            where
                S: ::serde::Serializer,
            {
                serializer.serialize_str(&self.to_string())
            }
        }

        impl<'de> ::serde::Deserialize<'de> for $name {
            fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
            where
                D: ::serde::Deserializer<'de>,
            {
                let value =
                    <::std::string::String as ::serde::Deserialize>::deserialize(deserializer)?;
                value.parse().map_err(::serde::de::Error::custom)
            }
        }

        impl ::std::str::FromStr for $name {
            type Err = $crate::ParseHexHashError;

            fn from_str(value: &str) -> Result<Self, Self::Err> {
                fn decode_nibble(byte: u8) -> Option<u8> {
                    match byte {
                        b'0'..=b'9' => Some(byte - b'0'),
                        b'a'..=b'f' => Some(byte - b'a' + 10),
                        _ => None,
                    }
                }

                if value.len() != 64 {
                    return Err($crate::ParseHexHashError::InvalidLength);
                }
                if !value
                    .bytes()
                    .all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b))
                {
                    return Err($crate::ParseHexHashError::InvalidHex);
                }

                let mut bytes = [0u8; 32];
                for (idx, chunk) in value.as_bytes().chunks_exact(2).enumerate() {
                    let hi = decode_nibble(chunk[0])
                        .ok_or($crate::ParseHexHashError::InvalidHex)?;
                    let lo = decode_nibble(chunk[1])
                        .ok_or($crate::ParseHexHashError::InvalidHex)?;
                    bytes[idx] = (hi << 4) | lo;
                }
                Ok(Self(bytes))
            }
        }
    };
}
